name: 'Setup Bazel'
description: 'Setup and configure bazel for CI use'
author: 'Angular'

inputs:
  bazelrc:
    default: .bazelrc.user
    description: |
      The `bazelrc` file location to add the `repository_cache` flag to. Defaults
      to .bazelrc.user

runs:
  using: composite
  steps:
    - name: Configure action caching for bazel version downloaded by bazelisk
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      with:
        path: |
          ~/.cache/bazelisk
          ~/AppData/Local/bazelisk
        key: bazel-version-${{ hashFiles('**/.bazelversion') }}

    - name: Set Bazel repository cache path on Linux
      if: runner.os != 'Windows'
      shell: bash
      run: echo "BAZEL_REPO_CACHE=~/.cache/bazel_repo_cache" >> $GITHUB_ENV

    - name: Set Bazel repository cache path on Windows
      if: runner.os == 'Windows'
      shell: wsl-bash {0}
      run: echo "BAZEL_REPO_CACHE=~/.cache/bazel_repo_cache" >> $GITHUB_ENV

    - name: Setup CI bazelrc config on Linux
      if: runner.os != 'Windows'
      shell: bash
      run: |
        ./setup-bazel.sh "${{ inputs.bazelrc }}" "${{ env.BAZEL_REPO_CACHE }}"

    - name: Setup CI bazelrc config on Windows
      if: runner.os == 'Windows'
      shell: wsl-bash {0}
      run: |
        ./setup-bazel.sh "${{ inputs.bazelrc }}" "${{ env.BAZEL_REPO_CACHE }}"

    - name: Configure action caching for bazel repository cache
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      with:
        path: ${{ env.BAZEL_REPO_CACHE }}
        key: bazel-cache-${{ runner.os }}-${{ hashFiles('**/WORKSPACE') }}-${{ hashFiles('**/MODULE.bazel') }}
        restore-keys: |
          bazel-cache-${{ runner.os }}-
