name: 'Setup Bazel'
description: 'Setup and configure bazel for CI use'
author: 'Angular'

inputs:
  bazelrc:
    default: .bazelrc.user
    description: |
      The `bazelrc` file location to add the `repository_cache` flag to. Defaults
      to .bazelrc.user
runs:
  using: composite
  steps:
    - name: Configure action caching for bazel version downloaded by bazelisk
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      with:
        path: |
          ~/.cache/bazelisk
          ~/AppData/Local/bazelisk
        key: bazel-version-${{ hashFiles('**/.bazelversion') }}

    - name: Setup CI bazelrc config
      shell: bash
      run: |
        # Set the BAZEL_CACHE_PATH environment variable.
        BAZEL_CACHE_PATH="~/.cache/bazel_repo_cache"

        # Check if running on Windows and if WSL is available.
        # The 'wsl' command is only available on Windows with WSL installed.
        if [[ "$OSTYPE" == "msys" || "$OSTYPE" == "win32" ]] && command -v wsl &> /dev/null; then
          # If on Windows and WSL is available, convert the path using wslpath.
          # This is need to ensure that Bazel in WSL can use this path.
          BAZEL_CACHE_PATH=$(wsl exec wslpath -u "$BAZEL_CACHE_PATH")
        fi

        echo "Bazel cache path is: $BAZEL_CACHE_PATH"

        node $GITHUB_ACTION_PATH/setup-ci-bazelrc.mjs "${{ inputs.bazelrc }}" "$BAZEL_CACHE_PATH"

    - name: Configure action caching for bazel repository cache
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      with:
        path: ~/.cache/bazel_repo_cache
        key: bazel-cache-${{ runner.os }}-${{ hashFiles('**/WORKSPACE') }}-${{ hashFiles('**/MODULE.bazel') }}
        restore-keys: |
          bazel-cache-${{ runner.os }}-
